const cityMap = {
  "القاهره": "CAIRO",
  "الجيزه": "GIZA",
  "الإسكندريه": "ALEXANDRIA",
  "البحيره": "BEHIRA",
  "القليوبيه": "QALIUBIA",
  "الغربيه": "GHARBIA",
  "المنوفيه": "MONOUFIA",
  "دمياط": "DOMITTA",
  "الدقهليه": "DAKAHLIA",
  "كفر الشيخ": "KAFR EL SHEIKH",
  "مطروح": "MARSA MATROUH",
  "الإسماعيليه": "ISMAILIA",
  "السويس": "SUEZ",
  "بور سعيد": "PORT SAID",
  "الشرقيه": "SHARKIA",
  "الفيوم": "FAYOUM",
  "بني سويف": "BANI SWEIF",
  "المنيا": "MENIA",
  "أسيوط": "ASSIUT",
  "سوهاج": "SOUHAGE",
  "قنا": "QENA",
  "أسوان": "ASWAN",
  "الأقصر": "LOUXOR",
  "البحر الأحمر": "RED SEA",
  "الوادي الجديد": "NEW VALLLEY",
  "شمال سيناء": "NOURTH SINAI",
  "جنوب سيناء": "SOUTH SINAI"
};

module.exports = cityMap;
